-- Database initialization is handled by the connection context or manual setup.
-- If you need to create the database, run: CREATE DATABASE IF NOT EXISTS HR_DB;
-- USE SCHEMA HR_DB.PUBLIC;

-- Table to store Job Descriptions
CREATE OR REPLACE TABLE JOBS (
    JOB_ID STRING PRIMARY KEY,
    TITLE STRING,
    DESCRIPTION STRING,
    REQUIRED_SKILLS STRING,
    ASSESSMENT_QUESTIONS VARIANT, -- JSON array of questions [{id, text, options, answer}]
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Table for Admins
CREATE OR REPLACE TABLE ADMINS (
    USERNAME STRING PRIMARY KEY,
    PASSWORD STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Table to store Candidate Applications
CREATE OR REPLACE TABLE CANDIDATES (
    CANDIDATE_ID STRING PRIMARY KEY,
    JOB_ID STRING,
    NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    CITY STRING,
    STATE STRING,
    COUNTRY STRING,
    WORK_EXPERIENCE STRING,
    EDUCATION_LEVEL STRING,
    RESUME_URL STRING,
    ATS_SCORE FLOAT,
    ATS_PASS BOOLEAN,
    ASSESSMENT_SCORE FLOAT,
    ASSESSMENT_START_TIME TIMESTAMP_NTZ, -- Timer start
    ASSESSMENT_END_TIME TIMESTAMP_NTZ,   -- Timer end
    CHAT_TRANSCRIPT VARIANT,             -- Chat history
    SCREENING_SCORE FLOAT,               -- Chat score
    APPLICATION_SCORE FLOAT,
    FINAL_SCORE FLOAT,
    APPLICATION_DETAILS VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID)
);

-- View for Power BI
CREATE OR REPLACE VIEW RECRUITER_DASHBOARD_VIEW AS
SELECT 
    C.CANDIDATE_ID,
    C.NAME,
    J.TITLE AS JOB_ROLE,
    C.email,
    C.ATS_SCORE,
    C.ASSESSMENT_SCORE,
    C.APPLICATION_SCORE,
    C.FINAL_SCORE,
    C.CREATED_AT
FROM CANDIDATES C
JOIN JOBS J ON C.JOB_ID = J.JOB_ID
WHERE C.ATS_PASS = TRUE
ORDER BY C.FINAL_SCORE DESC;
